### ISSUE TITLE
As a user, I want to be able to join a group, so that I may interact with friends by listening to a group playlist.

### ISSUE THREAD

**Issue by denniskuzminer** [agile-dev-assignments/project-setup-team-gualaceo-toolset#3]
## Estimation of work
- TBD

## Acceptance criteria
- [ ] Giving multiple people access to the same playlist
- [ ] Allowing users to add new songs to the playlist 
- [ ] Allowing users to request that new songs be added if not given privileges

**Comment by ryan-bello** [comment]
Redundant
