### ISSUE TITLE
As a user, I would like to be able to create a group so that I can share a generated playlist with my friends. 

### ISSUE THREAD

**Issue by denniskuzminer** [agile-dev-assignments/project-setup-team-gualaceo-toolset#4]
## Estimation of work
- TBD

## Acceptance criteria
- [ ] Ability to share playlist by sending access codes 
- [ ] Group creator receiving rights to edit playlist (by default)
- [ ] Group creator giving rights to edit playlist  
- [ ] Group creator allowing playlist to be edited by anyone who joins

**Comment by ryan-bello** [comment]
Redundant
